# Generated by Django 2.0 on 2018-08-07 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0002_auto_20180807_0546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Phone_Number',
            field=models.IntegerField(),
        ),
    ]
