# Generated by Django 2.0 on 2018-08-07 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0004_auto_20180807_0556'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Phone_Number',
            new_name='phone_number',
        ),
    ]
