# Generated by Django 2.0 on 2018-08-07 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0006_auto_20180807_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Account_Balance',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(),
        ),
    ]
