# Generated by Django 2.0 on 2018-08-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0011_auto_20180807_0759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='Account_Balance',
            field=models.IntegerField(default=0),
        ),
    ]
