# Generated by Django 2.0 on 2018-08-07 08:33

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0012_auto_20180807_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default=1, max_length=128),
            preserve_default=False,
        ),
    ]
