# Generated by Django 2.0 on 2018-08-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0014_auto_20180807_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
