# Generated by Django 2.0 on 2018-08-07 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0015_auto_20180807_0842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
