# Generated by Django 2.1 on 2018-08-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0017_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.CharField(max_length=40)),
                ('type', models.CharField(max_length=3)),
                ('expires_in', models.BigIntegerField()),
            ],
            options={
                'db_table': 'tbl_access_token',
            },
        ),
        migrations.CreateModel(
            name='C2BRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('business_short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_ref_number', models.CharField(blank=True, max_length=50, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_c2b_requests',
                'verbose_name_plural': 'C2B Requests',
            },
        ),
        migrations.CreateModel(
            name='OnlineCheckout',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=20)),
                ('checkout_request_id', models.CharField(default='', max_length=50)),
                ('account_reference', models.CharField(default='', max_length=50)),
                ('transaction_description', models.CharField(blank=True, max_length=50, null=True)),
                ('customer_message', models.CharField(blank=True, max_length=100, null=True)),
                ('merchant_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('response_code', models.CharField(blank=True, max_length=5, null=True)),
                ('response_description', models.CharField(blank=True, max_length=100, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_online_checkout_requests',
                'verbose_name_plural': 'Online Checkout Requests',
            },
        ),
        migrations.CreateModel(
            name='OnlineCheckoutResponse',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('merchant_request_id', models.CharField(blank=True, max_length=50, null=True)),
                ('checkout_request_id', models.CharField(default='', max_length=50)),
                ('result_code', models.CharField(blank=True, max_length=5, null=True)),
                ('result_description', models.CharField(blank=True, max_length=100, null=True)),
                ('mpesa_receipt_number', models.CharField(blank=True, max_length=50, null=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tbl_online_checkout_responses',
                'verbose_name_plural': 'Online Checkout Responses',
            },
        ),
    ]
