# Generated by Django 2.0 on 2018-08-09 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0017_lesson'),
    ]

    operations = [
        migrations.CreateModel(
            name='C2BRequest',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(blank=True, max_length=20, null=True)),
                ('transaction_id', models.CharField(max_length=20, unique=True)),
                ('transaction_date', models.DateTimeField(blank=True, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True)),
                ('business_short_code', models.CharField(blank=True, max_length=20, null=True)),
                ('bill_ref_number', models.CharField(blank=True, max_length=50, null=True)),
                ('third_party_trans_id', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.BigIntegerField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'C2B Requests',
                'db_table': 'tbl_c2b_requests',
            },
        ),
    ]
