# Generated by Django 2.1 on 2018-08-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0018_authtoken_c2brequest_onlinecheckout_onlinecheckoutresponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnlinePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BusinessShortCode', models.PositiveIntegerField(default=0)),
                ('Password', models.CharField(max_length=60)),
                ('Timestamp', models.DateTimeField(auto_now=True)),
                ('CheckoutRequestID', models.CharField(max_length=90)),
            ],
        ),
        migrations.DeleteModel(
            name='C2BRequest',
        ),
    ]
