# Generated by Django 2.0 on 2018-08-10 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0019_validation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='BusinessShortCode',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='validation',
            name='MSISDN',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='validation',
            name='TransTime',
            field=models.BigIntegerField(),
        ),
    ]
