# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-27 10:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0019_auto_20180820_1223'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
