# Generated by Django 2.0 on 2018-08-10 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0020_auto_20180810_0620'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Validation',
        ),
    ]
