# Generated by Django 2.0 on 2018-08-10 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0021_delete_validation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(max_length=100)),
                ('TransTime', models.BigIntegerField()),
                ('TransAmount', models.FloatField()),
                ('BusinessShortCode', models.BigIntegerField()),
                ('BillRefNumber', models.CharField(max_length=100)),
                ('InvoiceNumber', models.CharField(max_length=100)),
                ('OrgAccountBalance', models.FloatField()),
                ('ThirdPartyTransID', models.CharField(max_length=100)),
                ('MSISDN', models.BigIntegerField()),
                ('FirstName', models.CharField(max_length=100)),
                ('MiddleName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
            ],
        ),
    ]
