# Generated by Django 2.0 on 2018-08-10 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0023_auto_20180810_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='TransID',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
