# Generated by Django 2.0 on 2018-08-10 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0024_auto_20180810_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validation',
            name='BillRefNumber',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='FirstName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='InvoiceNumber',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='LastName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='OrgAccountBalance',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='ThirdPartyTransID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='TransID',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='validation',
            name='TransactionType',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
