# Generated by Django 2.0 on 2018-08-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa', '0025_auto_20180810_0649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirmation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TransactionType', models.CharField(blank=True, max_length=500)),
                ('TransID', models.CharField(blank=True, max_length=500)),
                ('TransTime', models.BigIntegerField()),
                ('TransAmount', models.FloatField()),
                ('BusinessShortCode', models.BigIntegerField()),
                ('BillRefNumber', models.CharField(blank=True, max_length=500)),
                ('InvoiceNumber', models.CharField(blank=True, max_length=500)),
                ('OrgAccountBalance', models.CharField(blank=True, max_length=500)),
                ('ThirdPartyTransID', models.CharField(blank=True, max_length=500)),
                ('MSISDN', models.BigIntegerField()),
                ('FirstName', models.CharField(blank=True, max_length=500)),
                ('MiddleName', models.CharField(blank=True, max_length=500)),
                ('LastName', models.CharField(blank=True, max_length=500)),
            ],
        ),
    ]
